### ISSUE TITLE
Обсудить с командой, как будем работать с запросами например через Tanstack, и какой стейт-менеджер использовать, например Redux

### ISSUE THREAD

**Issue by Turell7** [Turell7/market#12]

**Comment by gigabyte1511** [comment]
Я за tanstack и redux. C toolKit редакс кажется не таким массивным

**Comment by Turell7** [comment]
Я ещё думаю axios подключить

**Comment by gigabyte1511** [comment]
Если так будет удобнее, то конечно. Правда я все запросы выполнял через fetch, но думаю, что разберусь и с axios-ом

**Comment by Turell7** [comment]
Я тоже с axios до этого не работал, но почитал, он позволит меньше кода писать, и проще обрабатывать ошибки, также не нужно будет в json и обратно данные переводить, axios это делает под капотом
