### ISSUE TITLE
0.1.0 Создать приложение сервера на node.js

### ISSUE THREAD

**Issue by Turell7** [Turell7/market#7]

**Comment by gigabyte1511** [comment]
Реализовано:
1. Подключение к базе данных
2. Получение всех товаров
3. Получение товара по id
4. Создание нового товара
5. Удаление товара
6. Редактирование товара

**Comment by Turell7** [comment]
Я вчера подёргал с фронта, через феч ошибку выдавал что то про Корс, я на server cors установил и все заработало.
