### ISSUE TITLE
0.2.1 Создать и подключить БД

### ISSUE THREAD

**Issue by Turell7** [Turell7/market#8]

**Comment by gigabyte1511** [comment]
Удалось запустить и настроить удаленное подключение к базе данных на сервере amazon ec2

**Comment by gigabyte1511** [comment]
Создана база данных с именем Market
Создан пользователь market, от имени которого выполняется изменение базы данных
Создана тестовая таблица products, содержащая в себе поля id, name, price, createdAt, updatedAt.

**Comment by Turell7** [comment]
Отлично
